trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'clean test aggregate'

  - script: dir target\site\serenity /s
    displayName: "Verificar contenido de serenity report"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target/site/serenity'
      ArtifactName: 'SerenityReports'